# Generated by Django 5.1.3 on 2024-11-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_issuedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedb',
            name='issue_category',
            field=models.CharField(choices=[('Electrical Maintenance', 'Electrical Maintenance'), ('Plumbing Maintenance', 'Plumbing Maintenance'), ('HVAC (Heating, Ventilation, and Air Conditioning)', 'HVAC (Heating, Ventilation, and Air Conditioning)'), ('Building & Structural Maintenance', 'Building & Structural Maintenance')], default='Electrical Maintenance', max_length=255),
        ),
    ]
