# Generated by Django 5.1.3 on 2024-11-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_issuedb_issue_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedb',
            name='reported_dept',
        ),
        migrations.AddField(
            model_name='issuedb',
            name='reported_dept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department'),
        ),
    ]
