# Generated by Django 5.1.3 on 2024-11-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_issuedb_reported_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedb',
            name='issue_category',
            field=models.CharField(choices=[('Electrical Maintenance', 'Electrical Maintenance'), ('Plumbing Maintenance', 'Plumbing Maintenance'), ('HVAC (Heating, Ventilation, and Air Conditioning)', 'HVAC (Heating, Ventilation, and Air Conditioning)'), ('Building & Structural Maintenance', 'Building & Structural Maintenance'), ('Furniture Maintenance', 'Furniture Maintenance'), ('IT & Computer Equipment Maintenance', 'IT & Computer Equipment Maintenance'), ('Landscape & Groundskeeping', 'Landscape & Groundskeeping'), ('Others', 'Others')], default='Electrical Maintenance', max_length=255),
        ),
    ]
