# Generated by Django 5.1.3 on 2024-12-04 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_issuedb_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedb',
            name='assigned_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='issuedb',
            name='reported_dept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to='myapp.department'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.issuedb')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
