# Generated by Django 5.1.3 on 2024-12-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedb',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned to Foreman', 'Assigned to Foreman'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
