# Generated by Django 5.1.3 on 2024-12-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_escalation_extensionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalation',
            name='status',
            field=models.CharField(choices=[('Escalation Pending', 'Escalation Pending'), ('Escalation Approved', 'Escalation Approved'), ('Escalation Rejected', 'Escalation Rejected')], default='Extension Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='extensionrequest',
            name='status',
            field=models.CharField(choices=[('Extension Pending', 'Extension Pending'), ('Extension Approved', 'Extension Approved'), ('Extension Rejected', 'Extension Rejected')], default='Extension Pending', max_length=20),
        ),
    ]
