# Generated by Django 5.1.3 on 2024-12-08 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_escalation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedb',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned to Foreman', 'Assigned to Foreman'), ('Assigned to Worker', 'Assigned to Worker'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Escalation Pending', 'Escalation Pending'), ('Escalation Approved', 'Escalation Approved'), ('Escalation Rejected', 'Escalation Rejected'), ('Extension Pending', 'Extension Pending'), ('Extension Approved', 'Extension Approved'), ('Extension Rejected', 'Extension Rejected')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.task')),
            ],
        ),
    ]
