# Generated by Django 5.1.3 on 2024-12-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_extensionrequest_assigned_foreman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionrequest',
            name='assigned_foreman',
        ),
    ]
