# Generated by Django 5.1.3 on 2024-12-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_extensionrequest_assigned_foreman'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedb',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
