# Generated by Django 5.1.3 on 2025-01-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_pushsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
