# Generated by Django 5.1.3 on 2025-02-02 06:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_issuedb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('asset_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetStock',
            fields=[
                ('stock_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('prev_maintenance_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('warranty_expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('maintenance_frequency', models.IntegerField(default=30)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.asset')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='PreventiveMaintenanceSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned to Foreman', 'Assigned to Foreman'), ('Assigned to Worker', 'Assigned to Worker'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='pending', max_length=20)),
                ('scheduled_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='myapp.asset')),
                ('assigned_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_issues', to='myapp.department')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='myapp.assetstock')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preventive Maintenance Schedule',
                'verbose_name_plural': 'Preventive Maintenance Schedules',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
