# Generated by Django 5.1.3 on 2025-02-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_asset_location_assetstock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='building',
        ),
        migrations.AddField(
            model_name='location',
            name='block',
            field=models.CharField(blank=True, choices=[('AC BLOCK', 'Academic Block'), ('AD BLOCK', 'Administrative Block'), ('JB BLOCK', 'Jubilee Block'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.CharField(blank=True, choices=[('ground', 'Ground Floor'), ('first', 'First Floor'), ('second', 'Second Floor'), ('third', 'Third Floor'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
