# Generated by Django 5.1.3 on 2025-02-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_location_building_location_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetstock',
            name='warranty_expiry_date',
        ),
        migrations.AlterField(
            model_name='assetstock',
            name='stock_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
