# Generated by Django 5.1.3 on 2025-02-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_assetstock_warranty_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstock',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance due', 'Maintenance due')], default='Active', max_length=50),
        ),
    ]
