# Generated by Django 5.1.3 on 2025-02-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_assetstock_prev_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstock',
            name='prev_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
