# Generated by Django 5.1.3 on 2025-02-02 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_assetstock_prev_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstock',
            name='prev_maintenance_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assetstock',
            name='stock_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
