# Generated by Django 5.1.3 on 2025-02-02 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_assetstock_prev_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetstock',
            name='maintenance_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department'),
        ),
    ]
