# Generated by Django 5.1.3 on 2025-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_assetstock_maintenance_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstock',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance due', 'Maintenance due'), ('Maintenance Scheduled', 'Maintenance Scheduled')], default='Active', max_length=50),
        ),
    ]
