# Generated by Django 5.1.3 on 2025-03-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='issue_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
