# Generated by Django 5.1.3 on 2025-03-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_notification_issue_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstock',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance Due', 'Maintenance Due'), ('Maintenance Scheduled', 'Maintenance Scheduled')], default='Active', max_length=50),
        ),
    ]
